# ------------------------------------------------------------------------------------------------------------------------------------
# Name: Shivam Janda
# Date: November 28, 2022
# Program: SYSA-3204
# Description: Test cases exported from Selenium ide.
# ------------------------------------------------------------------------------------------------------------------------------------
# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service as ChromeService  # added
from webdriver_manager.chrome import ChromeDriverManager  # added
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLab5shivam():
  @classmethod
  def setup_method(cls):
    cls.browser = webdriver.Chrome()
    cls.vars = {};

  def teardown_method(cls):
    cls.browser.quit()
  
  def test_lab5shivam(self):
    # Test name: lab5_shivam
    # Step # | name | target | value
    # 1 | open | / |
    self.browser.get("https://magento.softwaretestingboard.com/")
    # 2 | setWindowSize | 1918x1030 |
    self.browser.set_window_size(1918, 1030)
    sleep(2)
    # 3 | click | id=ui-id-6 |
    self.browser.find_element(By.LINK_TEXT, "Gear").click()
    # 4 | click | linkText=Bags |
    self.browser.find_element(By.LINK_TEXT, "Bags").click()
    sleep(2)
    # 5 | click | css=.item:nth-child(1) .product-image-photo |
    self.browser.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .product-image-photo").click()
    sleep(2)
    # 6 | click | id=product-addtocart-button |
    self.browser.find_element(By.ID, "product-addtocart-button").click()
    sleep(2)
    # true or false if it sends a success message
    assert self.browser.find_element(By.XPATH, "//main/div/div[2]/div/div/div").text == "You added Push It Messenger Bag to your shopping cart."
    sleep(2)
    # 7 | click | css=.showcart |
    self.browser.find_element(By.CSS_SELECTOR, ".showcart").click()
    sleep(2)
    # 8 | close |  |
    self.browser.close()

  def test_lab5shivamtwo(self):
    # Test name: lab5_shivam_two
    # Step # | name | target | value
    # 1 | open | / |
    self.browser.get("https://magento.softwaretestingboard.com/")
    # 2 | setWindowSize | 1918x1030 |
    self.browser.set_window_size(1918, 1030)
    sleep(2)
    # 3 | click | id=ui-id-25 |
    self.browser.find_element(By.LINK_TEXT, "Gear").click()
    self.browser.find_element(By.LINK_TEXT, "Bags").click()
    sleep(2)
    # 4 | click | css=.item:nth-child(3) .product-image-photo |
    self.browser.find_element(By.CSS_SELECTOR, ".item:nth-child(3) .product-image-photo").click()
    sleep(2)
    # 5 | click | css=#product-addtocart-button > span |
    self.browser.find_element(By.ID, "product-addtocart-button").click()
    sleep(2)
    # true or false if it sends a success message
    assert self.browser.find_element(By.XPATH, "//main/div/div[2]/div/div/div").text == "You added Driven Backpack to your shopping cart."
    sleep(2)
    # 6 | click | css=.counter-number |
    self.browser.find_element(By.CSS_SELECTOR, ".showcart").click()
    sleep(2)
    # 7 | close |  |
    self.browser.close()
  
